server:
  port: 8084

spring:
  application:
    name: IDENTITY-SERVICE
  datasource:
    url: jdbc:postgresql://${HOST_DB}:${PORT_USER_DB}/${USER_DB_NAME}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      org.hibernate.envers:
        autoRegisterListeners: true
        audit_table_suffix: _history
        default_schema: user_history
        store_data_at_delete: true

  flyway:
    enabled: true
    baseline-on-migrate: true

application:
  security:
    jwt:
      secret-key: ${TOKEN_SIGNING_KEY}
      expiration: ${TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${TOKEN_REFRESH_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

otel:
  exporter:
    otlp:
      endpoint: ${OTLP_EXPORTER_ENDPOINT:http://localhost:4318}
  traces:
    exporter: otlp
  metrics:
    exporter: otlp