CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER                                   NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)                              NOT NULL,
    type           VARCHAR(20)                               NOT NULL,
    script         VARCHAR(1000)                             NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)                              NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER                                   NOT NULL,
    success        BOOLEAN                                   NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(200)                            NOT NULL,
    password VARCHAR(200)                            NOT NULL,
    role     VARCHAR(200),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

CREATE TABLE directories
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id BIGINT,
    user_id   BIGINT,
    name      VARCHAR(255),
    CONSTRAINT directories_pkey PRIMARY KEY (id)
);

CREATE TABLE files
(
    directory_id BIGINT,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT,
    uuid         UUID,
    name         VARCHAR(255),
    CONSTRAINT files_pkey PRIMARY KEY (id)
);