@startuml
title Работа с файлами/директориями

actor "Пользователь" as User
participant "API" as API
participant "File-Storage-Service" as FS
participant "File_DB" as FDB
participant "File_History_DB" as FHDB
participant "Minio_DB" as MDB

== Успешное сохранение ==
User -> API : Запрос на сохранение данных
API -> FS : Передача данных для обработки

FS -> FDB : Сохранение данных
FS -> FHDB : Запись в историю (в той же транзакции)
FDB --> FS : Ответ: статус 201 (данные сохранены)

FS -> MDB : Сохранение данных
MDB --> FS : Ответ: статус 201 (данные сохранены)
FS --> API : Ответ: данные сохранены


== Ошибка при сохранении в Minio ==
User -> API : Запрос на сохранение данных
API -> FS : Передача данных для обработки

group Транзакция 1: Работа с базой данных
FS -> FDB : Сохранение метаданных файла
FS -> FHDB : Запись в историю (в той же транзакции)
FDB --> FS : Ответ: успех
end

group Транзакция 2: Работа с Minio (ОШИБКА)
FS -> MDB : Сохранение файловых данных
MDB --> FS : Ошибка: не удалось сохранить файл
end

group Компенсирующие действия
FS -> FS : Запуск компенсирующей транзакции
FS -> FDB : Удаление метаданных файла
FS -> FHDB : Запись в историю об откате (DELETE операция)
FDB --> FS : Ответ: успех
FS -> MDB : Откат (если файл частично загружен - удаление)
MDB --> FS : Ответ: успех
end

FS --> API : Ошибка: не удалось сохранить файл
API --> User : Ошибка: попробуйте позже


== Успешное переименование ==
User -> API : Ввод данных
API -> FS : Передача данных для обработки
FS -> FDB : Проверка на существование
FDB --> FS : Ответ: статус 200 (данные существуют)

FS -> FDB : Смена имени
FS -> FHDB : Запись в историю (в той же транзакции)
FDB --> FS : Ответ: статус 200 (данные переименованы)
FS --> API : Ответ: данные переименованы

@enduml