@startuml
title Регистрация/авторизация пользователя

actor "Пользователь" as User
participant "API" as API
participant "Identity-Service" as IS
participant "Person_DB" as PDB
participant "Person_History_DB" as PHDB
participant "File-Storage-Service" as FS
participant "File_DB" as FDB
participant "File_History_DB" as FHDB

== Успешная регистрация ==
User -> API : Ввод регистрационных данных
API -> IS : Передача данных для обработки

IS -> PDB : Сохранение данных пользователя
IS -> PHDB : Запись в историю (в той же транзакции)
PDB --> IS : Ответ: данные сохранены
IS --> API : Ответ: статус 201 (данные сохранены)

API -> FS : Запрос на создание root-директории
FS -> FDB : Создание директории
FDB --> FS : Ответ: Директория создана
FS -> FHDB : Запись в историю (в той же транзакции)
FS --> API: Ответ: статус 200 (директория создана)

== Ошибка при запросе в БД при регистрации ==
User -> API : Ввод данных
API -> IS : Передача данных для обработки

group Транзакция начинается
IS -> PDB : Сохранение данных пользователя
IS -> PHDB : Запись в историю (подготовка)
PDB --> IS : Ошибка: не удалось сохранить данные
end

group Откат транзакции
IS -> PDB : Rollback
IS -> PHDB : Rollback (автоматически)
end

IS --> API : Ошибка: регистрация не удалась (данные не сохранены)
API --> User : Ошибка: регистрация не удалась. Попробуйте позже.


== Ошибка при запросе в БД при создании директории ==
User -> API : Ввод данных
API -> IS : Передача данных для обработки

IS -> PDB : Сохранение данных пользователя
IS -> PHDB : Запись в историю (в той же транзакции)
PDB --> IS : Ответ: данные сохранены
IS --> API : Ответ: статус 201 (данные сохранены)

API -> FS : Запрос на создание root-директории

group Транзакция начинается
FS -> FDB : Создание root-директории
FS -> FHDB : Запись в историю (в той же транзакции)
FDB --> FS : Ошибка: директория не создана
end

group Откат транзакции
FS -> FDB : Rollback
FS -> FHDB : Rollback (автоматически)
end

FS --> API : Ошибка: создание директории не удалось (директория создана)
API -> IS : Запрос на удаление пользователя

group Откат транзакции
IS -> PDB : Компенсирующая транзакция: удаление пользователя
IS -> PHDB : Запись в историю (в той же транзакции)
PDB --> IS : Ответ: пользователь удален
IS --> API : Ответ: статус 200 (пользователь удален)
end

API --> User : Ошибка: регистрация не удалась. Попробуйте позже.

@enduml