@startuml
title Авторизация пользователя

actor "Пользователь" as User
participant "API" as API
participant "Identity-Service" as IS
participant "Person_DB" as PDB
participant "Person_History_DB" as PHDB

== Успешная авторизация ==
User -> API : Ввод пользовательских данных
API -> IS : Передача данных для обработки
IS -> PDB : Проверка на существование
PDB --> IS : Ответ: статус 200 (данные существуют)
IS --> API : Ответ: JWT Token

== Ошибка при запросе в БД при авторизации ==
User -> API : Ввод данных
API -> IS : Передача данных для обработки

group Транзакция начинается
IS -> PDB : Проверка данных пользователя
IS -> PHDB : Запись в историю (подготовка)
PDB --> IS : Ошибка: данные не найдены
end

group Откат транзакции
IS -> PDB : Rollback
IS -> PHDB : Rollback (автоматически)
end

IS --> API : Ошибка: авторизация не удалась. Данные не найдены
API --> User : Ошибка: Данные не найдены

@enduml