@startuml
title Регистрация/авторизация пользователя

actor "Пользователь" as User
participant "API" as API
participant "Identity-Service" as IS
participant "Person_DB" as PDB
participant "Person_History_DB" as PHDB

== Успешная регистрация ==
User -> API : Ввод регистрационных данных
API -> IS : Передача данных для обработки

IS -> PDB : Сохранение данных пользователя
IS -> PHDB : Запись в историю (в той же транзакции)
PDB --> IS : Ответ: статус 201 (данные сохранены)
IS --> API : Ответ: данные сохранены

== Успешная авторизация ==
User -> API : Ввод пользовательских данных
API -> IS : Передача данных для обработки
IS -> PDB : Проверка на существование
PDB --> IS : Ответ: статус 200 (данные существуют)
IS --> API : Ответ: JWT Token

== Ошибка при запросе в БД при регистрации/авторизации ==
User -> API : Ввод данных
API -> IS : Передача данных для обработки

group Транзакция начинается
IS -> PDB : Сохранение данных пользователя
IS -> PHDB : Запись в историю (подготовка)
PDB --> IS : Ошибка: не удалось сохранить данные
end

group Откат транзакции
IS -> PDB : Rollback
IS -> PHDB : Rollback (автоматически)
end

IS --> API : Ошибка: регистрация не удалась (данные не сохранены)
API --> User : Ошибка: регистрация не удалась. Попробуйте позже.

@enduml