server:
  port: 8085

spring:
  application:
    name: API
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: basic

identity-service:
  url: "${IDENTITY_SERVICE_URL=http://identity-service:8084}"
file-storage-service:
  url: "${FILE_STORAGE_SERVICE_URL=http://file-storage-service:8082}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint: ${OTLP_EXPORTER_ENDPOINT:http://alloy:4318}
      protocol: http/protobuf
  logs:
    exporter: none
  metrics:
    exporter: none

logging:
  config: classpath:logback.xml