CREATE TABLE IF NOT EXISTS users
(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(200) UNIQUE NOT NULL,
    password VARCHAR(200) NOT NULL,
    create_date TIMESTAMP(6) WITHOUT TIME ZONE,
    last_modified TIMESTAMP(6) WITHOUT TIME ZONE,
    role VARCHAR(50)
);