spring.application.name=ai

spring.ai.ollama.base-url=http://localhost:11431
spring.ai.ollama.chat.model=gemma3:4b-it-q4_K_M
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.chat.options.top-p=0.9

spring.datasource.url=jdbc:postgresql://localhost:8891/ragdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.main.allow-circular-references=true

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.ollama=DEBUG
logging.level.org.hibernate.SQL=DEBUG