openapi: 3.0.3
info:
  title: LawDocs API
  version: 1.0.0
  description: Unified API gateway for LawDocs platform
servers:
  - url: http://localhost:8085
paths:
  /v1/auth/register:
    post:
      tags: [ Auth ]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'

  /v1/auth/login:
    post:
      tags: [ Auth ]
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  schemas:
    Role:
      type: string
      enum: [ USER, ADMIN ]
    RegisterRequest:
      type: object
      required: [ role, email, password, firstname, lastname ]
      properties:
        role: { $ref: '#/components/schemas/Role' }
        email: { type: string, format: email }
        password: { type: string }
        firstname: { type: string }
        lastname: { type: string }
    AuthenticationRequest:
      type: object
      required: [ email, password ]
      properties:
        email: { type: string, format: email }
        password: { type: string }
    AuthenticationResponse:
      type: object
      properties:
        token: { type: string }
        refreshToken: { type: string }
        tokenType: { type: string, example: "Bearer" }
        userId: {type: integer, format: int64}
    ErrorResponse:
      type: object
      properties:
        statusCode: { type: integer }
        message: { type: string }
  responses:
    BadRequest:
      description: Invalid input
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
    Conflict:
      description: User already exists
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
    Unauthorized:
      description: Invalid credentials
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }