@startuml Consultation with User Check
title Консультация с AI + проверка принадлежности файлов

participant "Telegram" as Telegram
participant "Telegram Bot" as Bot
participant "Backend" as back
participant "Database" as db

autonumber

Telegram -> Bot: Передача initData
Bot -> back: Передача initData
back -> back: Валидация initData с помощью bot_token и извлечение telegram id пользователя
back -> db: Запрос пользователя из БД или создание новго
db -> back: Получение пользователя из БД
back -> back: Генерация пары JWT-токенов
back -> Bot:  Установка пары токенов в cookies, ответ 200

@enduml